export const CHOSE_MOVIE_FROM_DROPDOWN = 'CHOSE_MOVIE_FROM_DROPDOWN';
export const SET_MOVIES_DATA = 'SET_MOVIES_DATA';
export const SET_IS_VISIBLE = 'SET_IS_VISIBLE';
export const SET_LOADING = 'SET_LOADING';
