export * from './BlockTitle';
export * from './BodyCV';
export * from './HeaderCV';
export * from './ContactCV';
export * from './EducationCV';
export * from './LanguagesCV';
export * from './PetProjectsCV';
export * from './TechnicalSkillsCV';
export * from './WorkCV';
